# Generated by Django 2.1 on 2019-03-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0002_auto_20190327_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookie',
            options={'verbose_name': 'Cookie', 'verbose_name_plural': 'Cookies'},
        ),
    ]
